services:
  - type: web
    name: garena-proxy
    runtime: python
    repo: https://github.com/7i67ihmj/LuanOri-Permanent-Lock  # Thay bằng repo của bạn
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Permanent:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
